/**
 * Default emoji shortcode set.
 *
 * A curated GitHub-flavored mapping of `:name:` aliases to their unicode
 * counterparts. Importing this file does not eagerly extend the parser
 * registry — the inline parser pulls entries from {@link DEFAULT_EMOJI_MAP}
 * lazily via a one-time merge in {@link parser/inline.ts}, so apps that
 * never parse a shortcode pay nothing beyond the reference cost of this
 * object literal.
 *
 * Entries are GitHub aliases; some unicode characters appear under multiple
 * names (`thumbsup` / `+1`) intentionally so familiar prose round-trips.
 */
export const DEFAULT_EMOJI_MAP: Readonly<Record<string, string>> = Object.freeze({
  // ── Faces ────────────────────────────────────────────────────────────
  smile: '😄',
  smiley: '😃',
  grinning: '😀',
  laughing: '😆',
  joy: '😂',
  rofl: '🤣',
  blush: '😊',
  innocent: '😇',
  wink: '😉',
  relaxed: '☺️',
  yum: '😋',
  sunglasses: '😎',
  heart_eyes: '😍',
  kissing_heart: '😘',
  thinking: '🤔',
  hushed: '😯',
  no_mouth: '😶',
  expressionless: '😑',
  unamused: '😒',
  pensive: '😔',
  worried: '😟',
  confounded: '😖',
  tired_face: '😫',
  weary: '😩',
  pleading_face: '🥺',
  cry: '😢',
  sob: '😭',
  rage: '😡',
  angry: '😠',
  triumph: '😤',
  fearful: '😨',
  cold_sweat: '😰',
  scream: '😱',
  exploding_head: '🤯',
  flushed: '😳',
  upside_down_face: '🙃',
  zany_face: '🤪',
  partying_face: '🥳',
  nerd_face: '🤓',
  face_with_monocle: '🧐',
  shushing_face: '🤫',
  zipper_mouth_face: '🤐',
  star_struck: '🤩',
  hugs: '🤗',
  vomiting_face: '🤮',
  sleeping: '😴',

  // ── Hands & body ─────────────────────────────────────────────────────
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  ok_hand: '👌',
  pinched_fingers: '🤌',
  victory_hand: '✌️',
  crossed_fingers: '🤞',
  metal: '🤘',
  call_me_hand: '🤙',
  point_left: '👈',
  point_right: '👉',
  point_up: '👆',
  point_down: '👇',
  point_up_2: '☝️',
  raised_hand: '✋',
  raised_back_of_hand: '🤚',
  vulcan_salute: '🖖',
  wave: '👋',
  clap: '👏',
  raised_hands: '🙌',
  open_hands: '👐',
  pray: '🙏',
  handshake: '🤝',
  muscle: '💪',
  selfie: '🤳',
  eyes: '👀',
  brain: '🧠',
  ear: '👂',

  // ── Symbols & marks ──────────────────────────────────────────────────
  heart: '❤️',
  blue_heart: '💙',
  green_heart: '💚',
  yellow_heart: '💛',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  orange_heart: '🧡',
  broken_heart: '💔',
  sparkling_heart: '💖',
  two_hearts: '💕',
  cupid: '💘',
  gift_heart: '💝',
  fire: '🔥',
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  zap: '⚡',
  boom: '💥',
  collision: '💥',
  tada: '🎉',
  confetti_ball: '🎊',
  rocket: '🚀',
  comet: '☄️',
  bulb: '💡',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  watch: '⌚',
  alarm_clock: '⏰',
  stopwatch: '⏱️',
  timer_clock: '⏲️',

  // ── Status / check / cross ───────────────────────────────────────────
  check: '✅',
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  ballot_box_with_check: '☑️',
  x: '❌',
  negative_squared_cross_mark: '❎',
  heavy_multiplication_x: '✖️',
  warning: '⚠️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  bangbang: '‼️',
  interrobang: '⁉️',
  question: '❓',
  grey_question: '❔',
  exclamation: '❗',
  grey_exclamation: '❕',
  info: 'ℹ️',
  o: '⭕',

  // ── Tech / dev ───────────────────────────────────────────────────────
  bug: '🐛',
  ant: '🐜',
  spider: '🕷️',
  computer: '💻',
  desktop_computer: '🖥️',
  keyboard: '⌨️',
  mouse: '🖱️',
  printer: '🖨️',
  floppy_disk: '💾',
  cd: '💿',
  dvd: '📀',
  minidisc: '💽',
  electric_plug: '🔌',
  battery: '🔋',
  satellite: '📡',
  abacus: '🧮',

  // ── Tools / objects ──────────────────────────────────────────────────
  wrench: '🔧',
  hammer: '🔨',
  hammer_and_wrench: '🛠️',
  pick: '⛏️',
  gear: '⚙️',
  nut_and_bolt: '🔩',
  toolbox: '🧰',
  paintbrush: '🖌️',
  crayon: '🖍️',
  pencil: '✏️',
  pencil2: '✏️',
  black_nib: '✒️',
  fountain_pen: '🖋️',
  memo: '📝',
  scroll: '📜',
  clipboard: '📋',
  pushpin: '📌',
  paperclip: '📎',
  triangular_ruler: '📐',
  straight_ruler: '📏',
  bookmark: '🔖',
  bookmark_tabs: '📑',
  ledger: '📒',
  closed_book: '📕',
  green_book: '📗',
  blue_book: '📘',
  orange_book: '📙',
  books: '📚',
  notebook: '📓',
  book: '📖',
  open_book: '📖',
  newspaper: '📰',
  package: '📦',
  envelope: '✉️',
  email: '📧',
  inbox_tray: '📥',
  outbox_tray: '📤',
  link: '🔗',
  paperclip2: '🖇️',

  // ── Security / locks ─────────────────────────────────────────────────
  lock: '🔒',
  lock_with_ink_pen: '🔏',
  closed_lock_with_key: '🔐',
  unlock: '🔓',
  key: '🔑',
  key2: '🗝️',
  shield: '🛡️',
  bow_and_arrow: '🏹',

  // ── Money ────────────────────────────────────────────────────────────
  moneybag: '💰',
  dollar: '💵',
  yen: '💴',
  euro: '💶',
  pound: '💷',
  credit_card: '💳',
  receipt: '🧾',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',

  // ── Weather / nature ─────────────────────────────────────────────────
  globe: '🌍',
  globe_with_meridians: '🌐',
  earth_americas: '🌎',
  earth_asia: '🌏',
  earth_africa: '🌍',
  sun: '☀️',
  partly_sunny: '⛅',
  cloud: '☁️',
  cloud_with_rain: '🌧️',
  cloud_with_lightning: '🌩️',
  cloud_with_snow: '🌨️',
  thunder_cloud_and_rain: '⛈️',
  umbrella: '☂️',
  closed_umbrella: '🌂',
  snowflake: '❄️',
  snowman: '⛄',
  fog: '🌫️',
  rainbow: '🌈',
  fire2: '🔥',
  ocean: '🌊',
  droplet: '💧',
  sweat_drops: '💦',
  moon: '🌙',
  full_moon: '🌕',
  new_moon: '🌑',
  new_moon_with_face: '🌚',
  full_moon_with_face: '🌝',

  // ── Food & drink ─────────────────────────────────────────────────────
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  wine_glass: '🍷',
  cocktail: '🍸',
  champagne: '🍾',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  taco: '🌮',
  burrito: '🌯',
  cake: '🎂',
  birthday: '🎂',
  cookie: '🍪',
  doughnut: '🍩',
  popcorn: '🍿',
  apple: '🍎',
  green_apple: '🍏',
  banana: '🍌',
  strawberry: '🍓',
  watermelon: '🍉',

  // ── Animals ──────────────────────────────────────────────────────────
  dog: '🐕',
  cat: '🐈',
  mouse2: '🐁',
  rat: '🐀',
  hamster: '🐹',
  rabbit: '🐰',
  fox: '🦊',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐄',
  pig: '🐖',
  frog: '🐸',
  monkey: '🐒',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  owl: '🦉',
  duck: '🦆',
  whale: '🐳',
  dolphin: '🐬',
  fish: '🐟',
  turtle: '🐢',
  snake: '🐍',
  butterfly: '🦋',
  honeybee: '🐝',
  bee: '🐝',
  unicorn: '🦄',
  dragon: '🐉',

  // ── Travel / places ──────────────────────────────────────────────────
  airplane: '✈️',
  rocket2: '🚀',
  ship: '🚢',
  car: '🚗',
  bus: '🚌',
  train: '🚂',
  bicycle: '🚲',
  motorcycle: '🏍️',
  oncoming_automobile: '🚘',
  fuelpump: '⛽',
  construction: '🚧',
  stop: '🛑',
  traffic_light: '🚦',
  vertical_traffic_light: '🚥',
  house: '🏠',
  office: '🏢',
  school: '🏫',
  hospital: '🏥',

  // ── Arrows & misc symbols ────────────────────────────────────────────
  arrow_right: '➡️',
  arrow_left: '⬅️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_upper_right: '↗️',
  arrow_upper_left: '↖️',
  arrow_lower_right: '↘️',
  arrow_lower_left: '↙️',
  leftwards_arrow_with_hook: '↩️',
  arrow_right_hook: '↪️',
  arrows_clockwise: '🔃',
  arrows_counterclockwise: '🔄',
  recycle: '♻️',
  back: '🔙',
  end: '🔚',
  on: '🔛',
  soon: '🔜',
  top: '🔝',

  // ── Geometric / circles ──────────────────────────────────────────────
  red_circle: '🔴',
  orange_circle: '🟠',
  yellow_circle: '🟡',
  green_circle: '🟢',
  blue_circle: '🔵',
  purple_circle: '🟣',
  brown_circle: '🟤',
  white_circle: '⚪',
  black_circle: '⚫',
  red_square: '🟥',
  orange_square: '🟧',
  yellow_square: '🟨',
  green_square: '🟩',
  blue_square: '🟦',
  purple_square: '🟪',
  brown_square: '🟫',
  white_large_square: '⬜',
  black_large_square: '⬛',
  diamond_shape_with_a_dot_inside: '💠',

  // ── Ops / signals ────────────────────────────────────────────────────
  rotating_light: '🚨',
  fire_engine: '🚒',
  ambulance: '🚑',
  loudspeaker: '📢',
  mega: '📣',
  bell: '🔔',
  no_bell: '🔕',
  speaker: '🔈',
  mute: '🔇',
  loud_sound: '🔊',
});
