export {
  type CreateTabBarConfig,
  createFloatingWindow,
  createPip,
  createSplitLayout,
  createTabBar,
  createWorkspaceManager,
  type FloatingWindowConfig,
  loadWorkspace,
  type Pane,
  type PipConfig,
  type SplitLayout,
  saveWorkspace,
  splitH,
  splitV,
  type TabConfig as CompatTabConfig,
  type Workspace,
  type WorkspaceManager,
  withFloatingWindows,
  withPip,
} from '../compat.js';
