export {
  type ActiveInteraction,
  createHorizonMouseModel,
  DEFAULT_EDGE_SNAP,
  DEFAULT_SNAP_CONFIG,
  type EdgeSnapConfig,
  getTabPreviewOrder,
  type HorizonMouseEffect,
  type HorizonMouseModel,
  type HorizonMouseMsg,
  horizonMouseUpdate,
  isDraggingFloat,
  isDraggingSeparator,
  isResizingFloat,
  type MouseDragData,
  type SnapConfig,
  shouldEnableMouse,
} from '../mouse.js';
export {
  createShellModel,
  getRegion,
  type ShellModel,
  type ShellMsg,
  type ShellRegion,
  type ShellUpdaters,
  shellUpdate,
} from '../shell.js';

// Geometry types are exported from primitives/index.ts — do not re-export here.

export {
  clampFloatingWindowFrame,
  type FloatingViewportBounds,
  type FloatingViewportRect,
  type FloatingWindowDefaults,
  type FloatingWindowDragState,
  type FloatingWindowFrame,
  type FloatingWindowResizeEdge,
  type FloatingWindowResizeState,
  getFloatingFullscreenArea,
  getFloatingViewportRect,
  getFloatingWorkArea,
  resizeFloatingWindowFrame,
  translateFloatingWindowFrame,
  translateFloatingWindowFromDragState,
} from '../floating-window-drag.js';
export {
  buildNavMap,
  createFocusModel,
  type Direction,
  type DirectionalNeighbors,
  extractPaneRects,
  type FocusModel,
  type FocusMsg,
  type FocusTrap,
  focusUpdate,
  focusUpdateResult,
  getActiveTrapBoundary,
  getFocusedId,
  getFocusHistory,
  getNavigableIds,
  getNeighbor,
  getTabOrder,
  isFocused,
  isTrapped,
  type PaneId,
  type PaneRect,
} from '../focus.js';
export {
  createKeybindingModel,
  getActivePane,
  type KeyBindingAction,
  type KeyBindingConfig,
  type KeyBindingModel,
  type KeyBindingMsg,
  keybindingHelp,
  keybindingUpdate,
  keybindingUpdateResult,
  resolveKeyAction,
} from '../keybindings.js';
export {
  createKeymap,
  findKeymapConflicts,
  type KeyBinding,
  type KeyCommand,
  type KeymapConflict,
  type KeymapModel,
  type KeymapPlatform,
  type KeymapScope,
  normalizeAccelerator,
  resolvePlatformKeyAction,
} from '../keymap.js';
export type {
  HorizonLayoutState,
  HorizonPersistenceConfig,
  LayoutPreset,
  PresetStore,
  SerializedConstraints,
  SerializedFloat,
  SerializedFocus,
  SerializedSplit,
  SerializedTabs,
  SerializedTile,
  SerializedWorkspace,
} from '../persistence.js';
export {
  buildLayoutState,
  CURRENT_LAYOUT_VERSION,
  createLayoutPersistenceConfig,
  createPresetStore,
  DEFAULT_SESSION_STATE,
  deletePreset,
  deserializeLayout,
  deserializePresets,
  extractFloatState,
  extractSplitState,
  extractTabState,
  extractWorkspaceState,
  listPresets,
  loadPreset,
  migrateLayout,
  savePreset,
  serializeLayout,
  serializePresets,
  validateLayoutState,
} from '../persistence.js';
export {
  createPipModel,
  isPipMinimized,
  type PipModel,
  type PipMsg,
  pipUpdate,
  pipUpdateResult,
} from '../pip.js';
export {
  createScrollRegionModel,
  extractScrollState,
  getScrollProgress,
  getScrollX,
  getScrollY,
  isScrolledToBottom,
  isScrolledToTop,
  type ScrollRegionModel,
  type ScrollRegionMsg,
  scrollRegionUpdate,
  scrollRegionUpdateResult,
} from '../scroll.js';
export {
  createSessionStore,
  listSessions,
  loadSession,
  type SessionPreview,
  type SessionRestorePolicy,
  type SessionStore,
  saveSession,
  type WorkspaceSession,
} from '../session.js';
export {
  getWindowChromeControlWidth,
  hitTestWindowChromeTitleBar,
  type RenderWindowChromeOptions,
  renderWindowChrome,
  type WindowChromeHitTarget,
  type WindowChromeTokens,
  windowChromeContract,
} from '../window-chrome.js';
export {
  applyWindowCommand,
  closeWindow,
  createDesktopWindow,
  type DesktopWindowState,
  fullscreenWindow,
  hideWindow,
  normalizeManagedWindow,
  restoreWindow,
  showWindow,
  type WindowChromeConfig,
  type WindowChromeControl,
  type WindowChromeHoverTarget,
  type WindowCommand,
  type WindowCommandSource,
  type WindowLifecycleOptions,
  type WindowLifecycleResult,
  type WindowMode,
  type WindowRestoreMode,
  type WindowRole,
  windowLifecycleUpdate,
} from '../window-lifecycle.js';
export {
  type WindowShelfAction,
  type WindowShelfConfig,
  type WindowShelfMeasureOptions,
  type WindowShelfStatusBarConfig,
  type WindowShelfTokens,
  windowShelf,
  windowShelfActionFromEvent,
  windowShelfContract,
  windowShelfReservedRows,
  windowShelfStatusBar,
} from '../window-shelf.js';
export {
  createWindowManager,
  encodeWindowEventId,
  getFrontmostWindow,
  getMinimizedWindows,
  getVisibleWindows,
  type ManagedWindow,
  type WindowManager,
  type WindowManagerBounds,
  type WindowManagerDiagnostic,
  type WindowManagerDiagnosticCode,
  type WindowManagerMsg,
  type WindowManagerOptions,
  type WindowManagerUpdateOutcome,
  windowManagerHoverAt,
  windowManagerMsgFromChromeEvent,
  windowManagerMsgFromWindowEvent,
  windowManagerUpdate,
  windowManagerUpdateResult,
} from '../windows.js';
export {
  createWorkspaceDescriptor,
  createWorkspaceModel,
  type DesktopWorkspaceModel,
  type DesktopWorkspaceMsg,
  desktopWorkspaceUpdate,
  getActiveWorkspace,
  movePaneToWorkspace,
  moveTabToWorkspace,
  moveWindowToWorkspace,
  normalizeWorkspaceModel,
  type WorkspaceDescriptor,
  type WorkspaceModel,
  type WorkspaceMsg,
  workspaceCount,
  workspaceUpdate,
  workspaceUpdateResult,
} from '../workspace.js';

export {
  type StateUpdateResult,
  stateUpdateResult,
} from './update.js';
