import { describe, expect, it } from 'vitest';
import {
  alert,
  autocomplete,
  badge,
  breadcrumb,
  button,
  card,
  checkbox,
  checkboxGroup,
  colorPicker,
  combobox,
  commandPalette,
  confirmDialog,
  createToastManager,
  dataTable,
  datePicker,
  divider,
  drawer,
  emptyState,
  list,
  modal,
  multiSelect,
  numberInput,
  optionListView,
  pagination,
  progressBar,
  radioGroup,
  rangeSlider,
  rating,
  segmentedControl,
  select,
  slider,
  spinner,
  tabs,
  tagInput,
  textarea,
  textInput,
  toggle,
  toggleGroup,
  tooltip,
  tree,
  formField,
  hovercard,
  popover,
  popoverGroup,
} from '../index.js';
import * as ui from '../index.js';

const componentBuilders = [
  button,
  textInput,
  textarea,
  checkbox,
  checkboxGroup,
  radioGroup,
  select,
  toggle,
  slider,
  autocomplete,
  combobox,
  datePicker,
  multiSelect,
  numberInput,
  rangeSlider,
  rating,
  segmentedControl,
  tagInput,
  colorPicker,
  formField,
  tabs,
  breadcrumb,
  pagination,
  commandPalette,
  optionListView,
  dataTable,
  tree,
  list,
  progressBar,
  spinner,
  card,
  divider,
  emptyState,
  badge,
  alert,
  tooltip,
  createToastManager,
  modal,
  confirmDialog,
  drawer,
  popover,
  popoverGroup,
  hovercard,
  toggleGroup,
];

const excludedBuilders = ['fileExplorer', 'markdownViewer', 'terminal', 'kanbanBoard', 'imageViewer', 'notificationCenter'] as const;

describe('@celestial/ui preview surface', () => {
  it('exports the curated 44 component builders', () => {
    expect(componentBuilders).toHaveLength(44);
    for (const builder of componentBuilders) expect(builder).toBeTypeOf('function');
  });

  it('does not export experimental components', () => {
    for (const name of excludedBuilders) expect(name in ui).toBe(false);
  });
});
