/**
 * Functional and Other Grammars
 */

import { functionCall, identifier, keywords, lineComment, numberLiteral, operators, punctuation, stringLiteral, whitespace } from '../grammar-helpers.js';
import type { LanguageGrammar } from '../types.js';
import { luaBlockComment, ocamlBlockComment } from './common.js';

// Lua

export const luaGrammar: LanguageGrammar = {
  name: 'lua',
  rules: [
    lineComment('--'),
    stringLiteral("'"),
    stringLiteral('"'),
    // Long strings
    { pattern: /\[\[[\s\S]*?\]\]/y, token: 'string' },
    numberLiteral(),
    keywords([
      'and',
      'break',
      'do',
      'else',
      'elseif',
      'end',
      'false',
      'for',
      'function',
      'goto',
      'if',
      'in',
      'local',
      'nil',
      'not',
      'or',
      'repeat',
      'return',
      'then',
      'true',
      'until',
      'while',
    ]),
    keywords(
      [
        'print',
        'type',
        'tostring',
        'tonumber',
        'pairs',
        'ipairs',
        'next',
        'select',
        'unpack',
        'table',
        'string',
        'math',
        'io',
        'os',
        'error',
        'pcall',
        'xpcall',
        'require',
        'setmetatable',
        'getmetatable',
        'rawget',
        'rawset',
        'rawlen',
        'rawequal',
        'assert',
        'collectgarbage',
        'load',
        'dofile',
      ],
      'builtin',
    ),
    functionCall(),
    identifier(),
    operators('+-*/%^#=<>~.'),
    whitespace(),
  ],
  states: [luaBlockComment()],
};

// Elixir

export const elixirGrammar: LanguageGrammar = {
  name: 'elixir',
  aliases: ['ex', 'exs'],
  rules: [
    lineComment('#'),
    { pattern: /:[a-zA-Z_][a-zA-Z_0-9?!]*/y, token: 'constant' },
    { pattern: /[A-Z][a-zA-Z_0-9.]*/y, token: 'namespace' },
    stringLiteral("'"),
    stringLiteral('"'),
    numberLiteral(),
    keywords([
      'after',
      'alias',
      'case',
      'catch',
      'cond',
      'def',
      'defmodule',
      'defp',
      'defmacro',
      'do',
      'else',
      'end',
      'false',
      'fn',
      'for',
      'if',
      'import',
      'in',
      'nil',
      'quote',
      'raise',
      'receive',
      'require',
      'rescue',
      'super',
      'throw',
      'true',
      'try',
      'unless',
      'unquote',
      'use',
      'when',
      'with',
    ]),
    keywords(['Enum', 'Map', 'List', 'String', 'Kernel', 'IO', 'Agent', 'Task'], 'builtin'),
    functionCall(),
    identifier(),
    operators('+-*/=<>!|&^:.'),
    whitespace(),
  ],
};

// Haskell

export const haskellGrammar: LanguageGrammar = {
  name: 'haskell',
  aliases: ['hs'],
  rules: [
    lineComment('--'),
    stringLiteral('"'),
    { pattern: /'(?:[^'\\]|\\.)'/y, token: 'string' },
    numberLiteral(),
    keywords([
      'case',
      'class',
      'data',
      'default',
      'deriving',
      'do',
      'else',
      'foreign',
      'if',
      'import',
      'in',
      'infix',
      'infixl',
      'infixr',
      'instance',
      'let',
      'module',
      'newtype',
      'of',
      'then',
      'type',
      'where',
    ]),
    keywords(['Int', 'Integer', 'Float', 'Double', 'Bool', 'Char', 'String', 'Maybe', 'Either', 'IO'], 'type'),
    keywords(['putStrLn', 'print', 'map', 'filter', 'foldl', 'foldr', 'pure', 'fmap'], 'builtin'),
    functionCall(),
    identifier(),
    operators('+-*/=<>:&|$!^.'),
    whitespace(),
  ],
};

// OCaml

export const ocamlGrammar: LanguageGrammar = {
  name: 'ocaml',
  aliases: ['ml', 'mli'],
  rules: [
    stringLiteral('"'),
    { pattern: /'(?:[^'\\]|\\.)'/y, token: 'string' },
    numberLiteral(),
    keywords([
      'and',
      'as',
      'assert',
      'begin',
      'class',
      'constraint',
      'do',
      'done',
      'downto',
      'else',
      'end',
      'exception',
      'external',
      'false',
      'for',
      'fun',
      'function',
      'functor',
      'if',
      'in',
      'include',
      'inherit',
      'initializer',
      'let',
      'match',
      'method',
      'module',
      'mutable',
      'new',
      'object',
      'of',
      'open',
      'or',
      'private',
      'rec',
      'sig',
      'struct',
      'then',
      'to',
      'true',
      'try',
      'type',
      'val',
      'virtual',
      'when',
      'while',
      'with',
    ]),
    keywords(['int', 'float', 'bool', 'char', 'string', 'list', 'array', 'option', 'result'], 'type'),
    keywords(['print_endline', 'Printf', 'List', 'Array', 'Option', 'Result'], 'builtin'),
    functionCall(),
    identifier(),
    operators('+-*/=<>@|:&^.'),
    whitespace(),
  ],
  states: [ocamlBlockComment()],
};

// R

export const rGrammar: LanguageGrammar = {
  name: 'r',
  aliases: ['rlang'],
  rules: [
    lineComment('#'),
    stringLiteral('"'),
    stringLiteral("'"),
    numberLiteral(),
    keywords([
      'if',
      'else',
      'for',
      'while',
      'repeat',
      'in',
      'next',
      'break',
      'function',
      'return',
      'switch',
      'tryCatch',
      'stop',
      'warning',
      'message',
      'library',
      'require',
      'source',
    ]),
    keywords(['TRUE', 'FALSE', 'NULL', 'NA', 'NA_integer_', 'NA_real_', 'NA_complex_', 'NA_character_', 'Inf', 'NaN'], 'constant'),
    keywords(['integer', 'double', 'complex', 'character', 'logical', 'numeric', 'list', 'data.frame', 'matrix', 'vector', 'factor', 'environment'], 'type'),
    keywords(
      [
        'c',
        'length',
        'nrow',
        'ncol',
        'dim',
        'names',
        'print',
        'cat',
        'paste',
        'paste0',
        'sprintf',
        'sum',
        'mean',
        'max',
        'min',
        'which',
        'apply',
        'sapply',
        'lapply',
        'tapply',
        'vapply',
        'mapply',
      ],
      'builtin',
    ),
    functionCall(),
    identifier(),
    operators('<->+=!&|:~$@^*/'),
    punctuation('()[]{}.,;'),
    whitespace(),
  ],
};

// Perl

export const perlGrammar: LanguageGrammar = {
  name: 'perl',
  aliases: ['pl'],
  rules: [
    lineComment('#'),
    // Regex literals
    { pattern: /\/(?:[^/\\]|\\.)+\/[gimsx]*/y, token: 'regexp' },
    // Heredoc markers (simplified)
    { pattern: /<<(?:~\s*)?'?[A-Z_][A-Z_0-9]*'?/y, token: 'string' },
    stringLiteral('"'),
    stringLiteral("'"),
    numberLiteral(),
    keywords([
      'use',
      'no',
      'require',
      'package',
      'sub',
      'my',
      'our',
      'local',
      'if',
      'elsif',
      'else',
      'unless',
      'while',
      'until',
      'for',
      'foreach',
      'do',
      'last',
      'next',
      'redo',
      'return',
      'die',
      'warn',
      'eval',
      'BEGIN',
      'END',
      'given',
      'when',
      'default',
    ]),
    keywords(
      [
        'print',
        'say',
        'chomp',
        'chop',
        'push',
        'pop',
        'shift',
        'unshift',
        'splice',
        'join',
        'split',
        'sort',
        'map',
        'grep',
        'defined',
        'ref',
        'length',
        'open',
        'close',
        'read',
        'write',
        'chdir',
        'mkdir',
        'rmdir',
      ],
      'builtin',
    ),
    // Variables ($scalar, @array, %hash)
    { pattern: /[$@%][a-zA-Z_][a-zA-Z_0-9]*/y, token: 'variable' },
    // Special variables ($_, $!, $@, etc.)
    { pattern: /\$[_!@&`'+\\/|,;.^~?*$<>0-9-]/y, token: 'variable' },
    functionCall(),
    identifier(),
    operators('=><+-*/%!&|^~.?:'),
    punctuation('()[]{}.,;'),
    whitespace(),
  ],
};
